name: CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('app/**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test project with Maven
        run: mvn -B package --file app/pom.xml

  deploy-the-webserver:
    name: Redeploy - Webhook call
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      - name: Sleep for 30 seconds
        run: sleep 30s
      - name: Curl the redeploy webhook
        run: curl -I ${{ secrets.DEPLOY_WEBHOOK_URL }}?token=${{ secrets.WEBHOOK_ACCESS_TOKEN }}
