name: CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test project with Maven
        run: mvn -B package --file pom.xml

  publish-job:
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: mvn -B package --file pom.xml -DskipTests
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging

  build-docker-image:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [build_and_test]

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Container image (amd64)
        run: docker buildx create --use; docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_REPO }}:amd64 .
      - name: Publish Docker image (amd64)
        run: docker push ${{ secrets.DOCKER_REPO }}:amd64
      - name: Build Container image (arm64)
        run: docker buildx build --platform linux/arm64 -t ${{ secrets.DOCKER_REPO }}:arm64 .
      - name: Publish Docker image (arm64)
        run: docker push ${{ secrets.DOCKER_REPO }}:arm64
      - name: Create manifest
        run: docker manifest create ${{ secrets.DOCKER_REPO }}:latest ${{ secrets.DOCKER_REPO }}:amd64 ${{ secrets.DOCKER_REPO }}:arm64
      - name: Push manifest
        run: docker manifest push ${{ secrets.DOCKER_REPO }}:latest